sandboxes:
  default:
    root: /home/thealchemist/repo/
    hasher: /tmp/.private/thealchemist/
    build:
      nprocs: 2
      arch: x86_64
      mountpoints: 
        - /proc
        - /dev/pts
        - /sys
      gear: true

infrastructure:
  ssh_gitery_hostname: git.alt
  ssh_gyle_hostname: gyle.alt
